create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  kind text not null default 'contact'
    check (kind in ('contact', 'b2b', 'order')),
  customer_name text not null
    check (char_length(customer_name) between 2 and 120),
  customer_email text not null
    check (char_length(customer_email) between 5 and 254),
  customer_phone text,
  message text not null
    check (char_length(message) between 5 and 4000),
  status text not null default 'new'
    check (status in ('new', 'in_progress', 'done', 'spam')),
  email_delivery_status text not null default 'not_configured'
    check (email_delivery_status in ('not_configured', 'sent', 'failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;
revoke all on table public.inquiries from public, anon, authenticated;
grant select, update, delete on table public.inquiries to authenticated;
grant insert, select, update on table public.inquiries to service_role;

drop policy if exists "Admin inquiry read" on public.inquiries;
drop policy if exists "Admin inquiry update" on public.inquiries;
drop policy if exists "Admin inquiry delete" on public.inquiries;
create policy "Admin inquiry read"
  on public.inquiries for select to authenticated
  using ((select public.is_admin()));
create policy "Admin inquiry update"
  on public.inquiries for update to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));
create policy "Admin inquiry delete"
  on public.inquiries for delete to authenticated
  using ((select public.is_admin()));

create index if not exists inquiries_created_at_idx
  on public.inquiries (created_at desc);
create index if not exists inquiries_status_created_at_idx
  on public.inquiries (status, created_at desc);
