CREATE TABLE IF NOT EXISTS public.order_status_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('confirmed', 'packed', 'sent', 'done', 'cancelled')),
  delivery_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (delivery_status IN ('pending', 'sent', 'failed')),
  provider_id TEXT,
  error_code TEXT,
  requested_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ,
  UNIQUE (order_id, status)
);

ALTER TABLE public.order_status_notifications ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.order_status_notifications FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.order_status_notifications_id_seq FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE public.order_status_notifications TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.order_status_notifications TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.order_status_notifications_id_seq TO service_role;

DROP POLICY IF EXISTS "Admin notification read" ON public.order_status_notifications;
CREATE POLICY "Admin notification read"
ON public.order_status_notifications
FOR SELECT
TO authenticated
USING ((SELECT public.is_admin()));

CREATE INDEX IF NOT EXISTS order_status_notifications_created_idx
ON public.order_status_notifications (created_at DESC);
